### ISSUE TITLE
Tiny code improvements

### ISSUE THREAD

**Issue by wolfadex** [3digitdev/swshdex#1]
https://github.com/3digitdev/swshdex/blob/a00be3a0d8565183212d56c895eff3f49b0c1371/src/Main.elm#L135

Don't initialize complex types like this, instead do `{ x4 = [], x2 = [], x0 = [], half = [], quarter = [] }`

---

`++` is the same as `List.append`

---

When decoding, include the value the decode failed on so that it can be logged out and possibly fixed. E.g.
```
_ ->
    JD.fail "Invalid PokemonType"
```
should be
```
_ ->
    JD.fail ("Invalid PokemonType: " ++ typeStr)
```

**Comment by 3digitdev** [comment]
Addressed in PR #2
